# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setEnabled(True)
        Settings.resize(620, 611)
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 601, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.left_btn.setFont(font)
        self.left_btn.setObjectName("left_btn")
        self.horizontalLayout.addWidget(self.left_btn)
        self.right_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.right_btn.setFont(font)
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout.addWidget(self.right_btn)
        self.crop_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.crop_btn.setFont(font)
        self.crop_btn.setObjectName("crop_btn")
        self.horizontalLayout.addWidget(self.crop_btn)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(50, 60, 521, 451))
        self.image.setAutoFillBackground(False)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.done_btn = QtWidgets.QPushButton(self.centralwidget)
        self.done_btn.setGeometry(QtCore.QRect(420, 550, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.done_btn.setFont(font)
        self.done_btn.setObjectName("done_btn")
        self.left_points = QtWidgets.QLabel(self.centralwidget)
        self.left_points.setGeometry(QtCore.QRect(40, 550, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.left_points.setFont(font)
        self.left_points.setText("")
        self.left_points.setObjectName("left_points")
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "MainWindow"))
        self.left_btn.setText(_translate("Settings", "Left"))
        self.right_btn.setText(_translate("Settings", "Right"))
        self.crop_btn.setText(_translate("Settings", "Crop"))
        self.done_btn.setText(_translate("Settings", "Done"))
